---

- hosts: localhost
  connection: local

  tasks:
    - name: install personal brew applications
      homebrew: name={{item}} state=latest
      with_items:
        - zsh
        - z

    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - sequel-pro
        - postico

    - name: set custom shell
      command: chsh -s /bin/zsh kirk 
      become: true

    - name: link to this configuration code
      file: src=/usr/local/superlumic/config
            dest=~/.superlumic-config
            state=link

    - name: apply global dotfiles
      git: repo=https://github.com/mrpossoms/dotfiles
           dest=~/.dotfiles
           update=yes
    - command: make -C ~/.dotfiles

    - name: apply sublime text settings
      git: repo=https://github.com/jacebrowning/sublime-settings
           dest="~/Library/Application Support/Sublime Text 3/Packages/User"
           update=no
    - file: src="~/Library/Application Support/Sublime Text 3/Packages/User"
            dest=~/.sublime-settings
            state=link

    - name: install personal python packages
      pip: executable=~/.pyenv/shims/pip
           name={{item.name}}
           version={{item.version}}
      with_items:
        - { name: thefuck, version: 3.11 }
        - { name: mine, version: 1.0 }

  roles:
    - profile-all
    - profile-developer

  vars:
    - git_user_name: Kirk Roerig
    - git_user_email: mr.possoms@gmail.com
