---

- name: install brew applications for all users
  homebrew: name={{item}} state=latest
  with_items:
    - vim

- name: install C/C++ dev libraries and headers
  homebrew: name={{item}} state=latest
  with_items:
    - glfw3

- name: install cask applications for all users
  homebrew_cask: name={{item}} state=present
  with_items:
    - google-chrome
    - slack
    - lastpass
    - sublime-text
    - atom
    - spotify
